---
    - import_playbook: configure_repos.yml
    - import_playbook: deploy_haproxy.yml
    - import_playbook: deploy_tomcat.yml
    - import_playbook: deploy_web.yml
    - import_playbook: deploy_db.yml
