---
    - name: deploy apache
    hosts: apps
    gather_facts: false
    become: true
    tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: enable apache at boot
      service:
        name: httpd
        enabled: yes
    - name: start apache
      service:
        name: httpd
        state: started
- name: index.html on app 1
hosts: app1
gather_facts: false
become: true

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.app1
    dest: /usr/share/tomcat/webapps/ansible/index.html

- name: index.html on app 1
hosts: app2
gather_facts: false
become: true

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.app2
    dest: /usr/share/tomcat/webapps/ansible/index.html
